### PR TITLE
Converted to NET Standard

### PR DESCRIPTION
**Pull request by eiaro**
I converted the library to NET Standard, as I need it to run on a Linux host. 

Builds good in VS2017 and on Ubuntu with Appveyor, also added a file for it so you can tag the repository.

### CODE REVIEW

**Comment by Mr-Markus** [comment]
Great work! exactly what i needed.

I thought it is not possible to work with SerialPort in netstandard. Could you explain how it will work on a Linux host?

**Comment by eiaro** [comment]
Not sure to be honest. I will be running it on a RPi sometime this week,
and I can write up something on the Wiki when I get through the hops.

**Comment by Mr-Markus** [comment]
I would like to get this running on a RPi, too.

But with .netstandard it couldn't run at the Moment, because if a Linux would call the necessary API for SerialPort it will throw a **PlatformNotSupportedException** 

See following from Microsofts new Guideline for developing class libraries: [https://docs.microsoft.com/de-de/dotnet/standard/library-guidance/cross-platform-targeting](https://docs.microsoft.com/de-de/dotnet/standard/library-guidance/cross-platform-targeting)

> Targeting .NET Standard, and successfully compiling your project, doesn't guarantee the library will run successfully on all platforms:
> 1. Platform-specific APIs will fail on other platforms. For example, Microsoft.Win32.Registry will succeed on Windows and throw PlatformNotSupportedException when used on any other OS.

As i saw that the System.IO.Port uses  Microsoft.Win32.Registry library. So a .netstandard implementation will not work directly on linux. But it should be possible with mono to run this netstandard implementation on Linux, because .netstandard2.0 is compatible with mono up from Version 5.4

I will be interested in your solution and your Feedback

**Comment by eiaro** [comment]
>
> .NET Core SDK (reflecting any global.json):
>
>  Version:   2.1.403
>
>  Commit:    04e15494b6
>
>
>> Runtime Environment:
>
>  OS Name:     raspbian
>
>  OS Version:  9
>
>  OS Platform: Linux
>
>  RID:         linux-arm
>
>  Base Path:   /home/pi/dotnet/sdk/2.1.403/
>
>
>> Host (useful for support):
>
>   Version: 2.1.5
>
>   Commit:  290303f510
>
>
>> .NET Core SDKs installed:
>
>   2.1.403 [/home/pi/dotnet/sdk]
>
>
>> .NET Core runtimes installed:
>
>   Microsoft.AspNetCore.All 2.1.5
>> [/home/pi/dotnet/shared/Microsoft.AspNetCore.All]
>
>   Microsoft.AspNetCore.App 2.1.5
>> [/home/pi/dotnet/shared/Microsoft.AspNetCore.App]
>
>   Microsoft.NETCore.App 2.1.5
>> [/home/pi/dotnet/shared/Microsoft.NETCore.App]
>
>
>> To install additional .NET Core runtimes or SDKs:
>
>   https://aka.ms/dotnet-download
>
>
I do however get errors. Same errors on VS2017 as well. Don't have time to
look into this tonight.

> Model/Endpoint.cs(16,21): error CS0246: The type or namespace name
> 'Cluster' could not be found (are you missing a using directive or an
> assembly reference?)
> [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]

Model/Endpoint.cs(18,21): error CS0246: The type or namespace name
> 'Cluster' could not be found (are you missing a using directive or an
> assembly reference?)
> [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]

Model/Endpoint.cs(20,21): error CS0246: The type or namespace name
> 'Cluster' could not be found (are you missing a using directive or an
> assembly reference?)
> [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]


Not quite sure on the intentions on this, so not trying to fix it. Btw,
this would be easily catchable by using Appveyor and it's free for open
source.

**Comment by Mr-Markus** [comment]
It seems that you don't have the Reference to ZigbeeNet.Zcl added in ZigbeeNet.CCZnp.
All three mentioned classes are within this library.

ZigbeeNet.ZCL contains all ZigbeeClusterLibrary specific stuff.
ZigbeeNet.CCZnp contains Texas Instrument specific classes for communicating with unpi via Z-Stack

I haven't worked with Appveyor, yet. But i will investigate some time in this and would try it.

**Comment by eiaro** [comment]
There is no Cluster.cs file in the project
[image: image.png]

Maybe it got lost on a commit?

**Comment by Mr-Markus** [comment]
You Need this file: https://github.com/Mr-Markus/ZigbeeNet/blob/master/src/ZigbeeNet.ZCL/Enums/Cluster.cs

The other files are in the same Directory.

Just for Info: I just restructured files in ZigbeeNet.CC by Layer and moved files to different Folders inside same Project

If you will try to build ZigbeeNet and ZigbeeNet.CC Project with AppVayor i suggest to open an issue in that repository for further discussions. Is it ok or does it still belong tu unpi-net?

**Comment by eiaro** [comment]
I see there is a new commit in and I'll give it a shot if I have time.

I'll make a PR with AppVeyor when it compiles. :)

**Comment by eiaro** [comment]
ZpiObject.cs(120,26): error CS0246: The type or namespace name 'DEBUG'
could not be found (are you missing a using directive or an assembly
reference?) [/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]
ZpiSREQ.cs(80,24): error CS0246: The type or namespace name 'DEBUG' could
not be found (are you missing a using directive or an assembly reference?)
[/home/pi/src/ZigbeeNet/src/ZigbeeNet.CCZnp/ZigbeeNet.CC.csproj]

**Pull request merged**
